name: GetDataBase
on: push
  branches:
    - action

jobs:
  builds:
    name: GetDataBase
    runs-on: ubuntu-latest
    steps:
      - name: Set up Golang Runtime
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
        id: go

      - name: Check out source code
      - uses: actions/checkout@v3
          with:
            ref: action

      - name: run
        run: go run main.go

      - name: test local
        run:
          - ls -l
          - cat ./data.json