name: GetDataBase
on:
  push:
    branches: [ action ]
  schedule:
    cron: "30 1 * * *"
jobs:
  builds:
    name: GetDataBase
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Golang Runtime
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - name: run
        run: go run main.go

      - name: commit
        uses: actions/checkout@v3
        with:
          path: .
          message: "Update database"
          branch: main
          hash: $(git rev-parse HEAD)