name: GetDataBase
on:
  schedule:
    - cron: '30 1 * * *'
jobs:
  builds:
    name: GetDataBase
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Golang Runtime
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - name: Run
        run: go run main.go

      - name: Commit Files
        run: |
          git config --global user.email "github-action@example.com"
          git config --global user.name "github-actions"
          git add .
          git commit -m "update data-`date +%m-%d-%H-%M`.json"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
